name: CI

on:
  push:
    branches: [ branch_docker_publish ]
  pull_request:
    branches: [ branch_docker_publish ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
  
    - name: Install required libs (Ubuntu)
      run: sudo apt-get install libev-dev libsqlite3-dev libmariadb-dev postgresql-client
      if: matrix.os == 'ubuntu-latest'
    - name: Install required libs (MacOS)
      run: |
        brew uninstall --ignore-dependencies libpq
        brew install libev pkg-config sqlite mariadb postgresql
      if: matrix.os == 'macOS-latest'

    - name: Setup OCaml
      uses: avsm/setup-ocaml@v1.0
      with:
        ocaml-version: 4.07.1 # optional, default is 4.08.1
    
    - name: Setup opam dependencies
      run: |
        OPAMJOBS=1 opam config report
        OPAMJOBS=1 opam install conf-libev
        OPAMJOBS=1 opam depext -yt
        OPAMJOBS=1 opam install -t . --deps-only
    
    - name: Build
      run: opam exec -- dune build @all
    
    - name: Tests
      run: opam exec -- dune runtest

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: zenoh-${{ matrix.os }}
        # Directory containing files to upload
        path: _build/default/install

  docker:
    name: Build and publish Docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download ubuntu-latest
        uses: actions/download-artifact@v1
        with:
          name: zenoh-ubuntu-latest
      - name: ls
        run: ls -al
      - name: ls zenoh-ubuntu-latest
        run: ls -al zenoh-ubuntu-latest*
      - name: Build and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: adlinktech/eclipse-zenoh
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
